
spring:
  application:
    name: hdtyglxt
  jackson:
    date-format: yyyy-MM-dd hh:mm:ss
    time-zone: GMT+8
  datasource:
    name: hdtyglxt
    url: jdbc:mysql://localhost:${MYSQL_PORT:3306}/livable?serverTimezone=GMT%2B8&useUnicode=true&characterEncoding=UTF-8
    username: root
    password: MyNewPass4!
    # druid
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: com.mysql.cj.jdbc.Driver
  messages:
    encoding: UTF-8
    basename: i18n/abt_messages
    use-code-as-default-message: true



  mvc:
    static-path-pattern: /**



#mybatis
mybatis:
  basepackage: com.example.hdtyglxt.mapper
  mapper-locations: ["classpath*:mapper/**/*.xml"]
  type-aliases-package: com.example.hdtyglxt.entity
  mappers: com.example.hdtyglxt.base.mapper.BaseMapper
  identity: MYSQL

logging:
  level:
    com.example.hdtyglxt.mapper: DEBUG

#端口号
server:
  port: 8579